---
apiVersion: v1
kind: Service
metadata:
    name: zechcodes-website
    labels:
        app: zechcodes-website
        tier: frontend
spec:
    type: NodePort
    ports:
      - port: 8000
        name: http
    selector:
        app: zechcodes-website
        tier: frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: zechcodes-website
    labels:
        app: zechcodes-website
    annotations:
        kubernetes.io/ingress.class: "traefik"
        cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
    tls:
      - hosts:
        - zech.codes
        secretName: zechcodes-website-cert
    rules:
      - host: zech.codes
        http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: zechcodes-website
                    port:
                      number: 8000
